POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Sixth Title",
  "author": "Sixth Author",
  "url": "www.url.etc",
  "likes": 0
}

###

GET http://localhost:3003/api/blogs
